<h2><span class="glyphicon glyphicon-road"></span>  Cadastrar Motorista</h2>

<?php
    $form = $this->form;

    if ($this->success){
        echo '<div class="alert alert-success">'. $this->success[0] .'<button type="button" class="close" data-dismiss="alert">*</button></div>';
    } else if ($this->error) {
        echo '<div class="alert alert-warning">'. $this->error[0] .'<button type="button" class="close" data-dismiss="alert">*</button></div>';
    }

    $this->formElementErrors()
            ->setMessageOpenFormat('<div class="alert alert-danger"><button type="button" class="close" data-dismiss="alert">*</button>')
            ->setMessageCloseString('</div>')
            ->render($form);

    $form->setAttribute('action', $this->url('motorista/default', array('controller' => 'motorista', 'action' => 'insert')));

    $form->prepare();

    echo $this->form()->openTag($form);

    echo $this->formCollection($form);

    echo $this->form()->closeTag();
?>