<?php

namespace Veiculo\Entity;

/**
 * VeiculoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VeiculoRepository extends \Doctrine\ORM\EntityRepository
{
}
