<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Trafegus | by nstech') ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo-trafegus-3.png'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

        <style>

            .margin-top {
                margin-top: 15px; /* Ajuste o valor conforme necessário */
            }

            .align-right {
                float: right; /* Faz o botão ir para a direita */
            }

            .custom-input:focus {
                border-color: #6a0dad;
                box-shadow: 0 0 5px rgba(106, 13, 173, 0.5);
                outline: none;
            }

            .form-control {
                background-color: #FCFBF7;
            }
            .navbar-custom {
                background-color: #6a0dad;
                border-color: #5a0b99;
            }

            .navbar-custom .navbar-brand,
            .navbar-custom .navbar-nav > li > a {
                color: #fff;
            }

            .navbar-custom .navbar-brand:hover,
            .navbar-custom .navbar-nav > li > a:hover {
                color: #000;
            }

            .navbar-brand img {
                width: 200px;
                height: auto;
                
            }

            body {
                padding-top: 100px;
            }

            footer {
                padding-top: 15px;
                padding-bottom: 15px;
                background-color: #f9f9f9;
                border-top: 1px solid #e5e5e5;
                text-align: center;
            }

            .container {
                margin-top: 20px;
            }
        </style>
    </head>
    <body>
        <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#">
                        <img src="<?php echo $this->basePath('img/logo-trafegus-4.svg') ?>" alt="Trafegus"/>
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class=""><a href="<?php echo $this->url('veiculo/default', ['controller' => 'veiculo', 'action' => 'index']) ?>">Veículos</a></li>
                        <li class=""><a href="<?php echo $this->url('motorista/default', ['controller' => 'motorista', 'action' => 'index']) ?>">Motoristas</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">
            <?php echo $this->content; ?>
            <hr>

            <footer>
                <p>&copy; 2024 - <?php echo date('Y') ?> por Trafegus Ltd. Todos os direitos reservados</p>
            </footer>
        </div>

        <?php echo $this->inlineScript() ?>
    </body>
</html>

